language: ruby
rvm:
  - 2.0.0
  - 2.1.0
script:
  - 'ruby spec/active_record/postgres/spec.rb'
  - 'ruby spec/sequel/postgres/spec.rb'
before_script:
  - psql -c 'create database minitest_parallel_db;' -U postgres
